### ISSUE TITLE
Firefox Legacy 68 p3 for Lion suddenly unresponsive

### ISSUE THREAD

**Issue by scrutinizer11** [parrotgeek1/FirefoxLegacy#14]
Perhaps it's not a FL issue, I'm investigating but after initially being fast it's crumbling all of sudden, halting to a crawl. Some applications, including Console and Pacifist, started to exhibit slower launch times and I don't know what to think but where I was able to wait for Console to open to the default view it shows kernel graphic engine errors like in one of the log files I attached. I'm not sure it's FL and if that's related to the latest version since I observed the same behaviour in p2. I have a 3rd party kext belonging to Little Snitch in /System. I see that Little Snitch's Network Monitor doesn't appear immediately when I click its menu bar icon. I don't know what's going on but posting the links just in case. Only restarting helps.

[Kernel-graphic-engine-MacOS Console](https://drive.google.com/file/d/1mFJjwEuEDBkWJN6lN2WfEZiXgLCeA9Qk/view?usp=drivesdk)

[Firefox-autorelease-MacOS Console](https://drive.google.com/file/d/158RBzVukscDbBMDx79KNbMqOPwfqJHna/view?usp=drivesdk)
[Firefox-Browser Console](https://drive.google.com/file/d/16ho4w5NA8YxHtEH_7RPJsN3k1FuZJEQK/view?usp=drivesdk)

**Comment by parrotgeek1** [comment]
Your GPU is dying according to the kernel logs. It's not FF Legacy. 

I know about those auto release memory leak messages. They are due to a bug in Firefox which was masked by a change in 10.9 (to automatically create autorelease pools) and was recently fixed after I reported it several years ago. Although technically there is memory being leaked per tab in 10.8 and 10.7, it's so little that it's harmless and it will go away when you close the tab.
